"use strict";

const WindowsEnum = {
    WindowAlignment: {
        WindowAlignmentAdaptive: 0,
        WindowAlignmentLeft: 1,
        WindowAlignmentCenter: 2,
        WindowAlignmentRight: 3
    },
    DWRITE_TEXT_ALIGNMENT: {
        DWRITE_TEXT_ALIGNMENT_LEADING: 0,
        DWRITE_TEXT_ALIGNMENT_TRAILING: 1,
        DWRITE_TEXT_ALIGNMENT_CENTER: 2,
        DWRITE_TEXT_ALIGNMENT_JUSTIFIED: 3
    },
    DWRITE_FONT_WEIGHT: {
        DWRITE_FONT_WEIGHT_THIN: 100,
        DWRITE_FONT_WEIGHT_EXTRA_LIGHT: 200,
        DWRITE_FONT_WEIGHT_ULTRA_LIGHT: 200,
        DWRITE_FONT_WEIGHT_LIGHT: 300,
        DWRITE_FONT_WEIGHT_SEMI_LIGHT: 350,
        DWRITE_FONT_WEIGHT_NORMAL: 400,
        DWRITE_FONT_WEIGHT_REGULAR: 400,
        DWRITE_FONT_WEIGHT_MEDIUM: 500,
        DWRITE_FONT_WEIGHT_DEMI_BOLD: 600,
        DWRITE_FONT_WEIGHT_SEMI_BOLD: 600,
        DWRITE_FONT_WEIGHT_BOLD: 700,
        DWRITE_FONT_WEIGHT_EXTRA_BOLD: 800,
        DWRITE_FONT_WEIGHT_ULTRA_BOLD: 800,
        DWRITE_FONT_WEIGHT_BLACK: 900,
        DWRITE_FONT_WEIGHT_HEAVY: 900,
        DWRITE_FONT_WEIGHT_EXTRA_BLACK: 950,
        DWRITE_FONT_WEIGHT_ULTRA_BLACK: 950
    },
    DWRITE_FONT_STYLE: {
        DWRITE_FONT_STYLE_NORMAL: 0,
        DWRITE_FONT_STYLE_OBLIQUE: 1,
        DWRITE_FONT_STYLE_ITALIC: 2
    }
};
